/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package LoginTest

import groovyx.net.http.HttpBuilder
import groovyx.net.http.optional.Download

import static groovyx.net.http.ContentTypes.JSON
import org.jsoup.nodes.Document
import groovyx.net.http.*
import static groovy.json.JsonOutput.prettyPrint
import static groovyx.net.http.HttpBuilder.configure

class App {
    static void main(String[] args) {

        def result = configure {
            request.uri = 'https://backend-site-operadora.rj.r.appspot.com'
            request.contentType = JSON[0]
        }.post{
            request.uri.path = '/login'
            request.body = [email: 'HospitalBomAtendimento@gmail.com.br', senha: '34$33']
            request.contentType = 'application/json'
            request.encoder 'application/x-www-form-urlencoded', NativeHandlers.Encoders.&form
        }

        def token = result.tokenDeAcesso

        def parameter = configure {
            request.uri = 'https://backend-site-operadora.rj.r.appspot.com'
        }.get{
            request.uri.path = '/demonstrativos'
            request.uri.query = [listarTodos : true , tokenDeAcesso : token]

        }

        def listaDemonstrativos = parameter.demonstrativos.url
        for(def demosnstrativos : listaDemonstrativos){
            def arquivoSplit = demosnstrativos.toString().split("/demonstrativoFiles([?!.,])fileName=")
            def arquivo = arquivoSplit[1].toString()
            def endpoint = "/demonstrativoFiles"

            File newFile = new File("/home/hyago/Área de Trabalho/Estudos/AceleraZG/WebCrawler/LoginTest/Downloads/${arquivo}.xlsx");
            File file = configure {
                request.uri = "https://backend-site-operadora.rj.r.appspot.com"
                request.uri.path = endpoint
                request.uri.query = [fileName : arquivo, tokenDeAcesso: token]
            }.get{
                Download.toFile(delegate, newFile)
            }
            file.createNewFile()
        }


    }

}
